alfavit_RU = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
smeshenie = int(input('Шаг шифровки: '))
itog = ''
with open("Text.txt", mode='r', encoding='utf-8') as T:
    with open('Encryption.txt', mode='w', encoding='utf-8') as ET:
        MyText = T.read().upper()
        for i in MyText:
            mesto = alfavit_RU.find(i)
            new_mesto = mesto + smeshenie
            if i in alfavit_RU:
                 itog += alfavit_RU[new_mesto]
            else:
                itog += i
        print(itog)
        ET.write(itog)


def search_index(text: str) -> dict:
    ker = dict()
    lst = list(set(text))
    for i in lst:
        ker[i] = text.count(i)
    ker = sorted(ker.items(), key=lambda x: x[1], reverse=True)
    return ker
text = open("cod4.txt", "r", encoding="utf-8").read()
d = search_index(text)
print(d)
text = text.replace("М", " ")
print(text)
text = text.replace(">", "и")
print(text)
text = text.replace("О", "е")
print(text)
text = text.replace("Е", "с")
print(text)
text = text.replace("1", "о")
print(text)
text = text.replace("r", "т")
print(text)
text = text.replace("Х", "н")
print(text)
text = text.replace("4", "а")
print(text)
text = text.replace("Д", "р")
print(text)
text = text.replace("a", "в")
print(text)
text = text.replace("c", "д")
print(text)
text = text.replace("2", "п")
print(text)
text = text.replace("8", "к")
print(text)
text = text.replace("У", "л")
print(text)
text = text.replace("\n", "ы")
print(text)
text = text.replace("Ф", "м")
print(text)
text = text.replace("Л", "я")
print(text)
text = text.replace("П", "ж")
print(text)
text = text.replace("7", "й")
print(text)
text = text.replace("А", "ь")
print(text)
text = text.replace("Р", "з")
print(text)
text = text.replace("t", "у")
print(text)
text = text.replace("5", "б")
print(text)
text = text.replace("И", "ф")
print(text)
text = text.replace("Й", "х")
print(text)
text = text.replace("b", "г")
print(text)
text = text.replace("К", "ю")
print(text)
text = text.replace("<", "ч")
print(text)
text = text.replace("Б", "э")
print(text)
text = text.replace("Ь", "щ")
print(text)
text = text.replace("Ы", "ш")
print(text)
text = text.replace("Ч", "ц")
print(text)
file = open('Decryption.txt', mode="w", encoding="UTF-8")
file.write(text)
file.close()
f = open('Key.txt', mode="w", encoding="UTF-8")
f.write("М : Space\n> : и\nО : е\nЕ : с\n1 : о\nr : т\nХ : н\n4 : а\nД : р\na : в\nс : д\n2 : п\nЗ : к"
        "\nУ : л\n\\n : ы\nФ : м\nЛ : я\nП : ж\n7 : й\nА : ь\nР : з\nt : у\n5 : б\nЙ : х\nb : г\nК : ю\n< : ч\nБ : э"
        "\nЬ : щ\nЫ : ш\nЧ : Ц")
f.close()